version: "2"
services:
  app:
    container_name: tambola-backend-mongo
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --port 27017
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"